spring:
  datasource:
    url: jdbc:h2:mem:buri_db
    username: buri
    password: 123
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
jwt:
  key: ${JWT-KEY}
  access-token-expiration: 60000
  refresh-token-expiration: 120000